### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by salunet** [lemehovskiy/parallax-background#2]
When i use the script i got high CPU usage. How can i fix that?

**Comment by lemehovskiy** [comment]
Hello @salunet ! Thanks for using my plugin. I will try optimize performance as soon as possible.

**Comment by salunet** [comment]
> Hello @salunet ! Thanks for using my plugin. I will try optimize performance as soon as possible.

That would be great!

**Comment by lemehovskiy** [comment]
Hello @salutet. Sorry for my "as soon as possible". If this is still relevant please let me know by providing more detailed configuration information.

**Comment by lemehovskiy** [comment]
@salunet I will probably close this issue. If it is still relevant, feel free to create a new one.
